# fly.toml app configuration file generated for workoutgenerator on 2023-10-06T19:18:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "workoutgenerator"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
